newsapp/urls.py
from django.urls import path
from newsapp.views import (
    index,
    TopicListView,
    TopicCreateView,
    TopicUpdateView,
    TopicDeleteView,
    NewspaperListView,
    NewspaperDetailView,
    NewspaperCreateView,
    NewspaperUpdateView,
    NewspaperDeleteView,
    RedactorListView,
    RedactorDetailView,
    RedactorCreationView,
    RedactorUpdateView,
    RedactorDeleteView,
    toggle_assign_to_newspaper,
)

urlpatterns = [
    path("", index, name="index"),
    path("topic/", TopicListView.as_view(), name="topic-list"),
    path("topic/create/", TopicCreateView.as_view(), name="topic-create"),
    path(
        "topic/<int:pk>/update/",
        TopicUpdateView.as_view(),
        name="topic-update",
    ),
    path(
        "topic/<int:pk>/delete/",
        TopicDeleteView.as_view(),
        name="topic-delete",
    ),
    path("newspaper/", NewspaperListView.as_view(), name="newspaper-list"),
    path(
        "newspaper/<int:pk>/",
        NewspaperDetailView.as_view(),
        name="newspaper-detail",
    ),
    path(
        "newspaper/create/",
        NewspaperCreateView.as_view(),
        name="newspaper-create",
    ),
    path(
        "newspaper/<int:pk>/update/",
        NewspaperUpdateView.as_view(),
        name="newspaper-update",
    ),
    path(
        "newspaper/<int:pk>/delete/",
        NewspaperDeleteView.as_view(),
        name="newspaper-delete",
    ),
    path("redactor/", RedactorListView.as_view(), name="redactor-list"),
    path(
        "redactor/<int:pk>/",
        RedactorDetailView.as_view(),
        name="redactor-detail",
    ),
    path(
        "redactor/create/",
        RedactorCreationView.as_view(),
        name="redactor-create",
    ),
    path(
        "redactor/<int:pk>/update/",
        RedactorUpdateView.as_view(),
        name="redactor-update",
    ),
    path(
        "redactor/<int:pk>/delete/",
        RedactorDeleteView.as_view(),
        name="redactor-delete",
    ),
    path(
        "redactor/<int:pk>/toggle_assign_to_newspaper",
        toggle_assign_to_newspaper,
        name="toggle_assign_to_newspaper",
    ),
]

app_name = "newsapp"

newspaper/urls.py
from django.urls import path
from newspaper.views import (
    index,
    TopicListView,
    TopicCreateView,
    TopicUpdateView,
    TopicDeleteView,
    NewspaperListView,
    NewspaperDetailView,
    NewspaperCreateView,
    NewspaperUpdateView,
    NewspaperDeleteView,
    RedactorListView,
    RedactorDetailView,
    RedactorCreationView,
    RedactorUpdateView,
    RedactorDeleteView,
    toggle_assign_to_newspaper,
)

urlpatterns = [
    path("", index, name="index"),
    path("topic/", TopicListView.as_view(), name="topic-list"),
    path("topic/create/", TopicCreateView.as_view(), name="topic-create"),
    path(
        "topic/<int:pk>/update/",
        TopicUpdateView.as_view(),
        name="topic-update",
    ),
    path(
        "topic/<int:pk>/delete/",
        TopicDeleteView.as_view(),
        name="topic-delete",
    ),
    path("newspaper/", NewspaperListView.as_view(), name="newspaper-list"),
    path(
        "newspaper/<int:pk>/",
        NewspaperDetailView.as_view(),
        name="newspaper-detail",
    ),
    path(
        "newspaper/create/",
        NewspaperCreateView.as_view(),
        name="newspaper-create",
    ),
    path(
        "newspaper/<int:pk>/update/",
        NewspaperUpdateView.as_view(),
        name="newspaper-update",
    ),
    path(
        "newspaper/<int:pk>/delete/",
        NewspaperDeleteView.as_view(),
        name="newspaper-delete",
    ),
    path("redactor/", RedactorListView.as_view(), name="redactor-list"),
    path(
        "redactor/<int:pk>/",
        RedactorDetailView.as_view(),
        name="redactor-detail",
    ),
    path(
        "redactor/create/",
        RedactorCreationView.as_view(),
        name="redactor-create",
    ),
    path(
        "redactor/<int:pk>/update/",
        RedactorUpdateView.as_view(),
        name="redactor-update",
    ),
    path(
        "redactor/<int:pk>/delete/",
        RedactorDeleteView.as_view(),
        name="redactor-delete",
    ),
    path(
        "redactor/<int:pk>/toggle_assign_to_newspaper",
        toggle_assign_to_newspaper,
        name="toggle_assign_to_newspaper",
    ),
]

app_name = "newspaper"

newspaper_agency/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from newspaper.views import login_view, logout_view

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("newspaper.urls", namespace="newspaper")),
    path("accounts/login/", login_view, name="login"),
    path("logout/", logout_view, name="logout"),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

newspaper/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse


class Topic(models.Model):
    name = models.CharField(max_length=255, unique=True)

    class Meta:
        ordering = ["name"]

    def __str__(self) -> str:
        return self.name


class Redactor(AbstractUser):
    years_of_experience = models.IntegerField(null=False, default=0)

    class Meta:
        verbose_name = "redactor"
        verbose_name_plural = "redactors"
        ordering = ["-years_of_experience"]

    def __str__(self) -> str:
        return f"{self.username} ({self.first_name} {self.last_name})"

    def get_absolute_url(self):
        return reverse("newspaper:redactor-detail", kwargs={"pk": self.pk})


class Newspaper(models.Model):
    title = models.CharField(max_length=255)
    content = models.TextField()
    published_date = models.DateField(auto_now=False)
    topic = models.ForeignKey(
        to=Topic, on_delete=models.CASCADE, related_name="newspaper"
    )
    redactor = models.ManyToManyField(to=Redactor, related_name="newspaper")

    class Meta:
        ordering = ["-published_date"]

    def __str__(self) -> str:
        return f"{self.topic.name} {self.title} {self.published_date}"

newsapp/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic

from newsapp.form import (
    NewspaperForm,
    RedactorCreationForm,
    RedactorYearsUpdateForm,
    TopicSearchForm,
    RedactorSearchForm,
    NewspaperSearchForm,
)
from newsapp.models import Redactor, Topic, Newspaper


@login_required
def index(request):
    num_redactors = Redactor.objects.count()
    num_topics = Topic.objects.count()
    num_newspapers = Newspaper.objects.count()

    num_visits = request.session.get("num_visits", 0)
    request.session["num_visits"] = num_visits + 1

    context = {
        "num_redactors": num_redactors,
        "num_topics": num_topics,
        "num_newspapers": num_newspapers,
        "num_visits": num_visits + 1,
    }

    return render(request, "newsapp/index.html", context=context)


class TopicListView(LoginRequiredMixin, generic.ListView):
    model = Topic
    paginate_by = 5
    queryset = Topic.objects.all()

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(TopicListView, self).get_context_data()

        name = self.request.GET.get("name", "")

        context["search_form"] = TopicSearchForm(
            initial={"name": name}
        )

        return context

    def get_queryset(self):
        form = TopicSearchForm(self.request.GET)

        if form.is_valid():
            return self.queryset.filter(
                name__icontains=form.cleaned_data["name"]
            )

        return self.queryset


class TopicCreateView(LoginRequiredMixin, generic.CreateView):
    model = Topic
    fields = "__all__"
    success_url = reverse_lazy("newsapp:topic-list")


class TopicUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Topic
    fields = "__all__"
    success_url = reverse_lazy("newsapp:topic-list")


class TopicDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Topic
    success_url = reverse_lazy("newsapp:topic-list")


class NewspaperListView(LoginRequiredMixin, generic.ListView):
    model = Newspaper
    paginate_by = 5
    queryset = Newspaper.objects.select_related("topic")

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(NewspaperListView, self).get_context_data()

        title = self.request.GET.get("title", "")

        context["search_form"] = NewspaperSearchForm(
            initial={"title": title}
        )

        return context

    def get_queryset(self):
        form = NewspaperSearchForm(self.request.GET)

        if form.is_valid():
            return self.queryset.filter(
                title__icontains=form.cleaned_data["title"]
            )

        return self.queryset


class NewspaperDetailView(LoginRequiredMixin, generic.DetailView):
    model = Newspaper


class NewspaperCreateView(LoginRequiredMixin, generic.CreateView):
    model = Newspaper
    form_class = NewspaperForm
    success_url = reverse_lazy("newsapp:newspaper-list")


class NewspaperUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Newspaper
    form_class = NewspaperForm
    success_url = reverse_lazy("newsapp:newspaper-list")


class NewspaperDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Newspaper
    success_url = reverse_lazy("newsapp:newspaper-list")


class RedactorListView(LoginRequiredMixin, generic.ListView):
    model = Redactor
    paginate_by = 5
    queryset = Redactor.objects.all()

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(RedactorListView, self).get_context_data(**kwargs)

        username = self.request.GET.get("username", "")

        context["search_form"] = RedactorSearchForm(
            initial={"username": username}
        )

        return context

    def get_queryset(self):
        form = RedactorSearchForm(self.request.GET)

        if form.is_valid():
            return self.queryset.filter(
                username__icontains=form.cleaned_data["username"]
            )

        return self.queryset


class RedactorDetailView(LoginRequiredMixin, generic.DetailView):
    model = Redactor
    queryset = Redactor.objects.prefetch_related("newspaper__topic")


class RedactorCreationView(LoginRequiredMixin, generic.CreateView):
    model = Redactor
    form_class = RedactorCreationForm


class RedactorUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Redactor
    form_class = RedactorYearsUpdateForm


class RedactorDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Redactor
    success_url = reverse_lazy("newsapp:redactor-list")


@login_required
def toggle_assign_to_newspaper(request, pk):
    redactor = Redactor.objects.get(id=request.user.id)
    if Newspaper.objects.get(id=pk) in redactor.newspaper.all():
        redactor.newspaper.remove(pk)
    else:
        redactor.newspaper.add(pk)
    return HttpResponseRedirect(
        reverse_lazy("newsapp:newspaper-detail", args=[pk])
    )

newspaper/views.py
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views import generic

from newspaper.forms import (
    NewspaperForm,
    RedactorCreationForm,
    RedactorUpdateForm,
    TopicSearchForm,
    RedactorSearchForm,
    NewspaperSearchForm,
    LoginForm,
)
from newspaper.models import Redactor, Topic, Newspaper


def login_view(request):
    form = LoginForm(request.POST or None)

    msg = None

    if request.method == "POST":

        if form.is_valid():
            username = form.cleaned_data.get("username")
            password = form.cleaned_data.get("password")
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect("/")
            else:
                msg = "Invalid credentials"
        else:
            msg = "Error validating the form"

    return render(request, "accounts/login.html", {"form": form, "msg": msg})


def logout_view(request):
    logout(request)

    return redirect("login")


@login_required
def index(request):
    redactor = Redactor.objects.all()
    newspaper = Newspaper.objects.all()
    num_redactors = redactor.count()
    num_topics = Topic.objects.count()
    num_newspapers = newspaper.count()

    num_visits = request.session.get("num_visits", 0)
    request.session["num_visits"] = num_visits + 1

    context = {
        "redactor_info": redactor.order_by("-years_of_experience")[:5],
        "newspaper_articles": newspaper.order_by("-published_date")[:5],
        "num_redactors": num_redactors,
        "num_topics": num_topics,
        "num_newspapers": num_newspapers,
        "num_visits": num_visits + 1,
    }

    return render(request, "newspaper/index.html", context=context)


class TopicListView(LoginRequiredMixin, generic.ListView):
    model = Topic
    paginate_by = 5
    queryset = Topic.objects.all()

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(TopicListView, self).get_context_data()

        name = self.request.GET.get("name", "")

        context["search_form"] = TopicSearchForm(initial={"name": name})

        return context

    def get_queryset(self):
        form = TopicSearchForm(self.request.GET)

        if form.is_valid():
            return self.queryset.filter(
                name__icontains=form.cleaned_data["name"]
            )

        return self.queryset


class TopicCreateView(LoginRequiredMixin, generic.CreateView):
    model = Topic
    fields = "__all__"
    success_url = reverse_lazy("newspaper:topic-list")


class TopicUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Topic
    fields = "__all__"
    success_url = reverse_lazy("newspaper:topic-list")


class TopicDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Topic
    success_url = reverse_lazy("newspaper:topic-list")


class NewspaperListView(LoginRequiredMixin, generic.ListView):
    model = Newspaper
    paginate_by = 5
    queryset = Newspaper.objects.select_related("topic")

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(NewspaperListView, self).get_context_data()

        title = self.request.GET.get("title", "")

        context["search_form"] = NewspaperSearchForm(initial={"title": title})

        return context

    def get_queryset(self):
        form = NewspaperSearchForm(self.request.GET)

        if form.is_valid():
            return self.queryset.filter(
                title__icontains=form.cleaned_data["title"]
            )

        return self.queryset


class NewspaperDetailView(LoginRequiredMixin, generic.DetailView):
    model = Newspaper


class NewspaperCreateView(LoginRequiredMixin, generic.CreateView):
    model = Newspaper
    form_class = NewspaperForm
    success_url = reverse_lazy("newspaper:newspaper-list")


class NewspaperUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Newspaper
    form_class = NewspaperForm
    success_url = reverse_lazy("newspaper:newspaper-list")


class NewspaperDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Newspaper
    success_url = reverse_lazy("newspaper:newspaper-list")


class RedactorListView(LoginRequiredMixin, generic.ListView):
    model = Redactor
    paginate_by = 5
    queryset = Redactor.objects.all()

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(RedactorListView, self).get_context_data(**kwargs)

        username = self.request.GET.get("username", "")

        context["search_form"] = RedactorSearchForm(
            initial={"username": username}
        )

        return context

    def get_queryset(self):
        form = RedactorSearchForm(self.request.GET)

        if form.is_valid():
            return self.queryset.filter(
                username__icontains=form.cleaned_data["username"]
            )

        return self.queryset


class RedactorDetailView(LoginRequiredMixin, generic.DetailView):
    model = Redactor
    queryset = Redactor.objects.prefetch_related("newspaper__topic")


class RedactorCreationView(LoginRequiredMixin, generic.CreateView):
    model = Redactor
    form_class = RedactorCreationForm
    success_url = reverse_lazy("newspaper:redactor-list")


class RedactorUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Redactor
    form_class = RedactorUpdateForm
    success_url = reverse_lazy("newspaper:redactor-list")


class RedactorDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Redactor
    success_url = reverse_lazy("newspaper:redactor-list")


@login_required
def toggle_assign_to_newspaper(request, pk):
    redactor = Redactor.objects.get(id=request.user.id)
    if Newspaper.objects.get(id=pk) in redactor.newspaper.all():
        redactor.newspaper.remove(pk)
    else:
        redactor.newspaper.add(pk)
    return HttpResponseRedirect(
        reverse_lazy("newspaper:newspaper-detail", args=[pk])
    )

templates/newsapp/newspaper_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete Newspaper</h1>

  <p>Are you sure you want to delete the newspaper: {{ newspaper.title }}?</p>

  <form action="" method="post">
    {% csrf_token %}
    <input type="submit" value="Yes, delete!" class="btn btn-danger">
    <a href="{% url 'newsapp:newspaper-detail' pk=newspaper.id %}" class="btn btn-success">Cancel</a>
  </form>
{% endblock %}

templates/newsapp/newspaper_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update, Create" }} Newspaper</h1>

  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input class="btn btn-primary" type="submit" value="Submit">
    <a href="{% url 'newsapp:newspaper-detail' pk=newspaper.id %}" class="btn btn-success">Cancel</a>
  </form>
{% endblock %}

templates/newsapp/newspaper_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>
    Newspaper Table
    <a style="float: right" href="{% url 'newsapp:newspaper-create' %}" class="btn btn-primary">Create</a>
  </h1>
  <form action="" method="get" class="form-inline">
    {{ search_form|crispy }}
    <input class="btn btn-primary" type="submit" value="🔍">
  </form>
  {% if newspaper_list %}
  <table class="table">
    <thead>
      <tr>
        <th>ID</th>
        <th>Title</th>
        <th>Content</th>
        <th>Date of publish</th>
        <th>Topic</th>
      </tr>
    </thead>
    <tbody>
      {% for newspaper in newspaper_list %}
        <tr>
          <td><a href="{% url "newsapp:newspaper-detail" pk=newspaper.id %}">{{ newspaper.id }}</a></td>
          <td>{{ newspaper.title }}</td>
          <td>{{ newspaper.content }}</td>
          <td>{{ newspaper.published_date }}</td>
          <td>{{ newspaper.topic.name }}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
  {% else %}
    <p>There are no newspapers in newspaper agency</p>
  {% endif %}
{% endblock %}

templates/newsapp/redactor_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete Redactor</h1>

  <p>Are you sure you want to delete the redactor: {{ redactor.first_name }} {{ redactor.last_name }}?</p>

  <form action="" method="post">
    {% csrf_token %}
    <input type="submit" value="Yes, delete!" class="btn btn-danger">
    <a href="{% url 'newsapp:topic-list' %}" class="btn btn-success">Cancel</a>
  </form>
{% endblock %}

templates/newsapp/redactor_detail.html
{% extends "base.html" %}

{% block content %}
  <p>
    <strong>{{ redactor.username }}</strong>
    ({{ redactor.first_name }} {{ redactor.last_name }})
    <strong>Years of experience: {{ redactor.years_of_experience }}</strong>
  </p>
  {% for newspaper in redactor.newspaper.all %}
    <hr>
    <p>
      <strong><a href="{% url "newsapp:newspaper-detail" pk=newspaper.id %}">ID: {{ newspaper.id }}</a></strong>
    </p>
    <p>Newspaper title: {{ newspaper.title }}</p>
    {% empty %}
      <p>Has no newspaper</p>
  {% endfor %}
  <a href="{% url 'newsapp:redactor-update' pk=redactor.id %}" class="btn btn-secondary">Update</a>
  <a href="{% url 'newsapp:redactor-delete' pk=redactor.id %}" class="btn btn-danger">Delete</a>
{% endblock %}

templates/newsapp/redactor_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update, Create" }} Redactor</h1>

  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input class="btn btn-primary" type="submit" value="Submit">
    <a href="{% url 'newsapp:redactor-list' %}" class="btn btn-success">Cancel</a>
  </form>
{% endblock %}

templates/newsapp/redactor_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>
    Redactors Table
    <a style="float: right" href="{% url 'newsapp:redactor-create' %}" class="btn btn-primary link-to-page">
        Create
    </a>
  </h1>

  <form action="" method="get" class="form-inline">
    {{ search_form|crispy }}
    <input class="btn btn-primary" type="submit" value="🔍">
  </form>

  {% if redactor_list %}
    <table class="table">
      <tr>
        <th>username</th>
        <th>Name</th>
        <th>Surname</th>
      </tr>
    <tbody>
      {% for redactor in redactor_list %}
        <tr>
          <td><a href="{% url 'newsapp:redactor-detail' pk=redactor.id %}">
            {{ redactor.username }}
            {% if user.id == driver.id %}
              <span>(Me)</span>
            {% endif %}
          </a></td>
          <td>{{ redactor.first_name }}</td>
          <td>{{ redactor.last_name }}</td>
        </tr>
      {% endfor %}
    </tbody>
    </table>
      {% else %}
        <p>There are no redactor in newspaper agency</p>
  {% endif %}
{% endblock %}

templates/newsapp/topic_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete Topic</h1>

  <p>Are you sure you want to delete the topic: {{ topic.name }}?</p>

  <form action="" method="post">
    {% csrf_token %}
    <input type="submit" value="Yes, delete!" class="btn btn-danger">
    <a href="{% url 'newsapp:topic-list' %}" class="btn btn-success">Cancel</a>
  </form>
{% endblock %}

templates/newsapp/topic_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update, Create" }} Topic</h1>

  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input class="btn btn-primary" type="submit" value="Submit">
    <a href="{% url 'newsapp:topic-list' %}" class="btn btn-success">Cancel</a>
  </form>
{% endblock %}

templates/newsapp/topic_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>
    Topics
    <a style="float: right" href="{% url 'newsapp:topic-create' %}" class="btn btn-primary">Create</a>
  </h1>

  <form action="" method="get" class="form-inline">
    {{ search_form|crispy }}
    <input class="btn btn-primary" type="submit" value="🔍">
  </form>

  {% if topic_list %}
    <table class="table">
      <thead>
        <tr>
          <th>ID</th>
          <th>Name</th>
          <th>Update</th>
          <th>Delete</th>
        </tr>
      </thead>
      <tbody>
        {% for topic in topic_list %}
          <tr>
            <td>{{ topic.id }}</td>
            <td>{{ topic.name }}</td>
            <td>
              <a href="{% url 'newsapp:topic-update' pk=topic.id %}">Update</a>
            </td>
            <td>
              <a href="{% url 'newsapp:topic-delete' pk=topic.id %}">Delete</a>
            </td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  {% else %}
    <p>No topics found</p>
  {% endif %}
{% endblock %}