newsapp/urls.py
from django.urls import path
from newsapp.views import (
    index,
    TopicListView,
    TopicCreateView,
    TopicUpdateView,
    TopicDeleteView,
    NewspaperListView,
    NewspaperDetailView,
    NewspaperCreateView,
    NewspaperUpdateView,
    NewspaperDeleteView,
    RedactorListView,
    RedactorDetailView,
    RedactorCreationView,
    RedactorUpdateView,
    RedactorDeleteView,
    toggle_assign_to_newspaper,
)

urlpatterns = [
    path("", index, name="index"),
    path("topic/", TopicListView.as_view(), name="topic-list"),
    path("topic/create/", TopicCreateView.as_view(), name="topic-create"),
    path(
        "topic/<int:pk>/update/",
        TopicUpdateView.as_view(),
        name="topic-update",
    ),
    path(
        "topic/<int:pk>/delete/",
        TopicDeleteView.as_view(),
        name="topic-delete",
    ),
    path("newspaper/", NewspaperListView.as_view(), name="newspaper-list"),
    path(
        "newspaper/<int:pk>/",
        NewspaperDetailView.as_view(),
        name="newspaper-detail",
    ),
    path(
        "newspaper/create/",
        NewspaperCreateView.as_view(),
        name="newspaper-create",
    ),
    path(
        "newspaper/<int:pk>/update/",
        NewspaperUpdateView.as_view(),
        name="newspaper-update",
    ),
    path(
        "newspaper/<int:pk>/delete/",
        NewspaperDeleteView.as_view(),
        name="newspaper-delete",
    ),
    path("redactor/", RedactorListView.as_view(), name="redactor-list"),
    path(
        "redactor/<int:pk>/",
        RedactorDetailView.as_view(),
        name="redactor-detail",
    ),
    path(
        "redactor/create/",
        RedactorCreationView.as_view(),
        name="redactor-create",
    ),
    path(
        "redactor/<int:pk>/update/",
        RedactorUpdateView.as_view(),
        name="redactor-update",
    ),
    path(
        "redactor/<int:pk>/delete/",
        RedactorDeleteView.as_view(),
        name="redactor-delete",
    ),
    path(
        "redactor/<int:pk>/toggle_assign_to_newspaper",
        toggle_assign_to_newspaper,
        name="toggle_assign_to_newspaper",
    ),
]

app_name = "newsapp"

newspaper_agency/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from newspaper.views import login_view, logout_view

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("newspaper.urls", namespace="newspaper")),
    path("accounts/login/", login_view, name="login"),
    path("logout/", logout_view, name="logout"),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/includes/footer-fullscreen.html
<footer class="py-5">
  <div class="container">
    <div class="row align-items-center justify-content-xl-between">
      <div class="col-xl-6">
        <div class="copyright text-center text-xl-left text-muted">
            <a target="_blank"
               href="https://github.com/HStakhiv"
               class="font-weight-bold ml-1" target="_blank">More Projects</a>
        </div>
      </div>
      <div class="col-xl-6">
        <div class="text-center text-xl-right text-muted">
           &copy; <a target="_blank" href="https://www.linkedin.com/in/hryhorii-stakhiv-232636171/">HStakhiv</a></a>
        </div>
      </div>
    </div>
  </div>
</footer>

templates/includes/footer.html
<footer class="footer">
  <div class="row align-items-center justify-content-xl-between">
    <div class="col-xl-6">
      <div class="text-center text-xl-left text-muted">
        <a href="https://github.com/HStakhiv"
           class="font-weight-bold ml-1" target="_blank">More Projects</a>
      </div>
    </div>
    <div class="col-xl-6">
      <div class="text-center text-xl-right text-muted">
        <a href="https://www.linkedin.com/in/hryhorii-stakhiv-232636171/"
           class="font-weight-bold ml-1" target="_blank"> &copy; HStakhiv</a>
      </div>
    </div>
  </div>
</footer>

templates/includes/navigation-fullscreen.html
<nav id="navbar-main" class="navbar navbar-horizontal navbar-transparent navbar-main navbar-expand-lg navbar-light">
  <div class="container">
    <a class="navbar-brand" href="/">
      <img src="/static/assets/img/brand/ui_design_newspap.svg" alt="Starter Logo.">
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-collapse" aria-controls="navbar-collapse" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="navbar-collapse navbar-custom-collapse collapse" id="navbar-collapse">
      <div class="navbar-collapse-header">
        <div class="row">
          <div class="col-6 collapse-brand">
            <a href="/">
              <img src="/static/assets/img/brand/news-n.png">
            </a>
          </div>
          <div class="col-6 collapse-close">
            <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbar-collapse" aria-controls="navbar-collapse" aria-expanded="false" aria-label="Toggle navigation">
              <span></span>
              <span></span>
            </button>
          </div>
        </div>
      </div>
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <a href="{% url 'login' %}" class="nav-link">
            <span class="nav-link-inner--text">Login</span>
          </a>
        </li>
      </ul>
      <hr class="d-lg-none" />
      <ul class="navbar-nav align-items-lg-center ml-lg-auto">
        <li class="nav-item">
          <a class="nav-link nav-link-icon" href="https://www.facebook.com/HryhoriiStakhiv"
             target="_blank" data-toggle="tooltip" data-original-title="Connect with me on Facebook">
            <i class="fab fa-facebook-square"></i>
            <span class="nav-link-inner--text d-lg-none">Facebook</span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link nav-link-icon" href="https://www.linkedin.com/in/hryhorii-stakhiv-232636171/"
             target="_blank" data-toggle="tooltip" data-original-title="Connect with me on LinkedIn">
            <i class="fab fa-linkedin"></i>
            <span class="nav-link-inner--text d-lg-none">LinkedIn</span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link nav-link-icon" href="https://t.me/HStakhiv"
             target="_blank" data-toggle="tooltip" data-original-title="Connect with me on Telegram">
            <i class="fab fa-telegram"></i>
            <span class="nav-link-inner--text d-lg-none">Telegram</span>
          </a>
        </li>
      </ul>
    </div>
  </div>
</nav>

templates/includes/navigation.html
<nav class="navbar navbar-top navbar-expand navbar-dark bg-primary border-bottom">
  <div class="container-fluid">
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <h1 class="text-white">
        Newspaper Agency Manager
      </h1>
      <!-- Navbar links -->
      <ul class="navbar-nav align-items-center  ml-md-auto ">
        <li class="nav-item d-xl-none">
          <!-- Sidenav toggler -->
          <div class="pr-3 sidenav-toggler sidenav-toggler-dark" data-action="sidenav-pin" data-target="#sidenav-main">
            <div class="sidenav-toggler-inner">
              <i class="sidenav-toggler-line"></i>
              <i class="sidenav-toggler-line"></i>
              <i class="sidenav-toggler-line"></i>
            </div>
          </div>
        </li>
      </ul>
      <ul class="navbar-nav align-items-center  ml-auto ml-md-0 ">
        <li class="nav-item dropdown">
          <a class="nav-link pr-0" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <div class="media align-items-center">
              <span class="avatar avatar-sm">
                <img alt="Image placeholder" src="/static/assets/img/theme/account.svg">
              </span>
              <div class="media-body  ml-2  d-none d-lg-block">
                <span class="mb-0 text-sm  font-weight-bold">
                  {{ request.user.username }}
                </span>
              </div>
            </div>
          </a>
          <div class="dropdown-menu  dropdown-menu-right ">
            <div class="dropdown-header noti-title">
              <h6 class="text-overflow m-0">Welcome!</h6>
            </div>
            <a href="{{ user.get_absolute_url }}" class="dropdown-item">
              <i class="ni ni-single-02"></i>
              <span>My profile</span>
            </a>
            {% if user.is_staff %}
              <a href="{% url 'admin:index' %}" class="dropdown-item">
                <i class="ni ni-settings"></i>
                <span>Admin panel</span>
              </a>
            {% endif %}
            <div class="dropdown-divider"></div>
            <a href="{% url 'logout' %}" class="dropdown-item">
              <i class="ni ni-user-run text-red"></i>
              <span>Logout</span>
            </a>
          </div>
        </li>
      </ul>
    </div>
  </div>
</nav>

templates/includes/pagination.html
{% load query_transform %}
{% if is_paginated %}
  <nav aria-label="...">
    <ul class="pagination justify-content-center mt-4">
      <li class="page-item {% if not page_obj.has_previous %} disabled {% endif %}">
          <a class="page-link"
             href="{% if page_obj.has_previous %}?{% query_transform request page=page_obj.previous_page_number %}{% endif %}">
            <i class="fas fa-angle-left"></i>
            <span class="sr-only">Previous</span>
          </a>
      </li>

      <li class="page-item active">
        <span class="page-link">{{ page_obj.number }}</span>
      </li>

      <li class="page-item">
        <span class="font-weight-bold">of</span>
      </li>

      <li class="page-item active">
        <span class="page-link">{{ paginator.num_pages }}</span>
      </li>

      <li class="page-item {% if not page_obj.has_next %} disabled {% endif %}">
          <a class="page-link"
             href="{% if page_obj.has_next %}?{% query_transform request page=page_obj.next_page_number %}{% endif %}">
            <i class="fas fa-angle-right"></i>
            <span class="sr-only">Next</span>
          </a>
      </li>
    </ul>
  </nav>
{% endif %}

templates/includes/scripts.html
  <script src="/static/assets/vendor/jquery/dist/jquery.min.js"></script>
  <script src="/static/assets/vendor/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
  <script src="/static/assets/vendor/js-cookie/js.cookie.js"></script>
  <script src="/static/assets/vendor/jquery.scrollbar/jquery.scrollbar.min.js"></script>
  <script src="/static/assets/vendor/jquery-scroll-lock/dist/jquery-scrollLock.min.js"></script>

templates/includes/sidenav.html
<nav class="sidenav navbar navbar-vertical  fixed-left  navbar-expand-xs navbar-light bg-white" id="sidenav-main">
  <div class="scrollbar-inner">
    <!-- Brand -->
    <div class="sidenav-header  align-items-center">
      <a class="navbar-brand" href="/">
        <img src="/static/assets/img/brand/ui_design_newspap.svg" class="navbar-brand-img" alt="Template Logo.">
      </a>
    </div>
    <div class="navbar-inner">
      <!-- Collapse -->
      <div class="collapse navbar-collapse" id="sidenav-collapse-main">
        <!-- Nav items -->
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link {% if request.path == '/' %} active {% endif %}" href="/">
              <i class="ni ni-tv-2 text-primary"></i>
              <span class="nav-link-text">Home</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link {% if request.path == '/newspaper/' %} active {% endif %}" href="{% url 'newspaper:newspaper-list' %}">
              <i class="ni ni-align-center text-red  "></i>
              <span class="nav-link-text">All newspapers</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link {% if request.path == '/redactor/' %} active {% endif %}" href="{% url 'newspaper:redactor-list' %}">
              <i class="ni ni-circle-08 text-orange"></i>
              <span class="nav-link-text">All redactors</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link {% if request.path == '/topic/' %} active {% endif %}" href="{% url 'newspaper:topic-list' %}">
              <i class="ni ni-book-bookmark text-green"></i>
              <span class="nav-link-text">All topics</span>
            </a>
          </li>
        </ul>

        <!-- Navigation -->
        <ul class="navbar-nav mb-md-3">
          <li class="nav-item">
            <a class="nav-link active active-pro"
               href="{% url 'logout' %}">
              <i class="ni ni-user-run text-red"></i>
              <span class="nav-link-text">Logout</span>
            </a>
          </li>
        </ul>
      </div>
    </div>
  </div>
</nav>