newsapp/urls.py
from django.urls import path
from newsapp.views import (
    index,
    TopicListView,
    TopicCreateView,
    TopicUpdateView,
    TopicDeleteView,
    NewspaperListView,
    NewspaperDetailView,
    NewspaperCreateView,
    NewspaperUpdateView,
    NewspaperDeleteView,
    RedactorListView,
    RedactorDetailView,
    RedactorCreationView,
    RedactorUpdateView,
    RedactorDeleteView,
    toggle_assign_to_newspaper,
)

urlpatterns = [
    path("", index, name="index"),
    path("topic/", TopicListView.as_view(), name="topic-list"),
    path("topic/create/", TopicCreateView.as_view(), name="topic-create"),
    path(
        "topic/<int:pk>/update/",
        TopicUpdateView.as_view(),
        name="topic-update",
    ),
    path(
        "topic/<int:pk>/delete/",
        TopicDeleteView.as_view(),
        name="topic-delete",
    ),
    path("newspaper/", NewspaperListView.as_view(), name="newspaper-list"),
    path(
        "newspaper/<int:pk>/",
        NewspaperDetailView.as_view(),
        name="newspaper-detail",
    ),
    path(
        "newspaper/create/",
        NewspaperCreateView.as_view(),
        name="newspaper-create",
    ),
    path(
        "newspaper/<int:pk>/update/",
        NewspaperUpdateView.as_view(),
        name="newspaper-update",
    ),
    path(
        "newspaper/<int:pk>/delete/",
        NewspaperDeleteView.as_view(),
        name="newspaper-delete",
    ),
    path("redactor/", RedactorListView.as_view(), name="redactor-list"),
    path(
        "redactor/<int:pk>/",
        RedactorDetailView.as_view(),
        name="redactor-detail",
    ),
    path(
        "redactor/create/",
        RedactorCreationView.as_view(),
        name="redactor-create",
    ),
    path(
        "redactor/<int:pk>/update/",
        RedactorUpdateView.as_view(),
        name="redactor-update",
    ),
    path(
        "redactor/<int:pk>/delete/",
        RedactorDeleteView.as_view(),
        name="redactor-delete",
    ),
    path(
        "redactor/<int:pk>/toggle_assign_to_newspaper",
        toggle_assign_to_newspaper,
        name="toggle_assign_to_newspaper",
    ),
]

app_name = "newsapp"

newspaper/urls.py
from django.urls import path
from newspaper.views import (
    index,
    TopicListView,
    TopicCreateView,
    TopicUpdateView,
    TopicDeleteView,
    NewspaperListView,
    NewspaperDetailView,
    NewspaperCreateView,
    NewspaperUpdateView,
    NewspaperDeleteView,
    RedactorListView,
    RedactorDetailView,
    RedactorCreationView,
    RedactorUpdateView,
    RedactorDeleteView,
    toggle_assign_to_newspaper,
)

urlpatterns = [
    path("", index, name="index"),
    path("topic/", TopicListView.as_view(), name="topic-list"),
    path("topic/create/", TopicCreateView.as_view(), name="topic-create"),
    path(
        "topic/<int:pk>/update/",
        TopicUpdateView.as_view(),
        name="topic-update",
    ),
    path(
        "topic/<int:pk>/delete/",
        TopicDeleteView.as_view(),
        name="topic-delete",
    ),
    path("newspaper/", NewspaperListView.as_view(), name="newspaper-list"),
    path(
        "newspaper/<int:pk>/",
        NewspaperDetailView.as_view(),
        name="newspaper-detail",
    ),
    path(
        "newspaper/create/",
        NewspaperCreateView.as_view(),
        name="newspaper-create",
    ),
    path(
        "newspaper/<int:pk>/update/",
        NewspaperUpdateView.as_view(),
        name="newspaper-update",
    ),
    path(
        "newspaper/<int:pk>/delete/",
        NewspaperDeleteView.as_view(),
        name="newspaper-delete",
    ),
    path("redactor/", RedactorListView.as_view(), name="redactor-list"),
    path(
        "redactor/<int:pk>/",
        RedactorDetailView.as_view(),
        name="redactor-detail",
    ),
    path(
        "redactor/create/",
        RedactorCreationView.as_view(),
        name="redactor-create",
    ),
    path(
        "redactor/<int:pk>/update/",
        RedactorUpdateView.as_view(),
        name="redactor-update",
    ),
    path(
        "redactor/<int:pk>/delete/",
        RedactorDeleteView.as_view(),
        name="redactor-delete",
    ),
    path(
        "redactor/<int:pk>/toggle_assign_to_newspaper",
        toggle_assign_to_newspaper,
        name="toggle_assign_to_newspaper",
    ),
]

app_name = "newspaper"

newspaper_agency/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from newspaper.views import login_view, logout_view

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("newspaper.urls", namespace="newspaper")),
    path("accounts/login/", login_view, name="login"),
    path("logout/", logout_view, name="logout"),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

newspaper/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse


class Topic(models.Model):
    name = models.CharField(max_length=255, unique=True)

    class Meta:
        ordering = ["name"]

    def __str__(self) -> str:
        return self.name


class Redactor(AbstractUser):
    years_of_experience = models.IntegerField(null=False, default=0)

    class Meta:
        verbose_name = "redactor"
        verbose_name_plural = "redactors"
        ordering = ["-years_of_experience"]

    def __str__(self) -> str:
        return f"{self.username} ({self.first_name} {self.last_name})"

    def get_absolute_url(self):
        return reverse("newspaper:redactor-detail", kwargs={"pk": self.pk})


class Newspaper(models.Model):
    title = models.CharField(max_length=255)
    content = models.TextField()
    published_date = models.DateField(auto_now=False)
    topic = models.ForeignKey(
        to=Topic, on_delete=models.CASCADE, related_name="newspaper"
    )
    redactor = models.ManyToManyField(to=Redactor, related_name="newspaper")

    class Meta:
        ordering = ["-published_date"]

    def __str__(self) -> str:
        return f"{self.topic.name} {self.title} {self.published_date}"

newspaper/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.core.exceptions import ValidationError

from newspaper.models import Redactor, Newspaper


class LoginForm(forms.Form):
    username = forms.CharField(
        widget=forms.TextInput(
            attrs={"placeholder": "Username", "class": "form-control"}
        )
    )
    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={"placeholder": "Password", "class": "form-control"}
        )
    )


class RedactorCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = Redactor
        fields = UserCreationForm.Meta.fields + (
            "years_of_experience",
            "first_name",
            "last_name",
        )

    def clean_years_of_experience(self):
        return validate_years_of_experience(
            self.cleaned_data["years_of_experience"]
        )


class RedactorUpdateForm(forms.ModelForm):
    class Meta:
        model = Redactor
        fields = ("years_of_experience", "first_name", "last_name")

    def clean_years_of_experience(self):
        return validate_years_of_experience(
            self.cleaned_data["years_of_experience"]
        )


def validate_years_of_experience(years_of_experience):
    if not (0 <= years_of_experience <= 80):
        raise ValidationError(
            "Ensure that the years of experience is between 0 and 80"
        )

    return years_of_experience


class DateInput(forms.DateInput):
    input_type = "date"


class NewspaperForm(forms.ModelForm):
    redactor = forms.ModelMultipleChoiceField(
        queryset=get_user_model().objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False,
    )
    published_date = forms.DateField(widget=DateInput)

    class Meta:
        model = Newspaper
        fields = "__all__"


class RedactorSearchForm(forms.Form):
    username = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Search by username"}),
    )


class NewspaperSearchForm(forms.Form):
    title = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Search by title"}),
    )


class TopicSearchForm(forms.Form):
    name = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Search by name"}),
    )

newspaper/views.py
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views import generic

from newspaper.forms import (
    NewspaperForm,
    RedactorCreationForm,
    RedactorUpdateForm,
    TopicSearchForm,
    RedactorSearchForm,
    NewspaperSearchForm,
    LoginForm,
)
from newspaper.models import Redactor, Topic, Newspaper


def login_view(request):
    form = LoginForm(request.POST or None)

    msg = None

    if request.method == "POST":

        if form.is_valid():
            username = form.cleaned_data.get("username")
            password = form.cleaned_data.get("password")
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect("/")
            else:
                msg = "Invalid credentials"
        else:
            msg = "Error validating the form"

    return render(request, "accounts/login.html", {"form": form, "msg": msg})


def logout_view(request):
    logout(request)

    return redirect("login")


@login_required
def index(request):
    redactor = Redactor.objects.all()
    newspaper = Newspaper.objects.all()
    num_redactors = redactor.count()
    num_topics = Topic.objects.count()
    num_newspapers = newspaper.count()

    num_visits = request.session.get("num_visits", 0)
    request.session["num_visits"] = num_visits + 1

    context = {
        "redactor_info": redactor.order_by("-years_of_experience")[:5],
        "newspaper_articles": newspaper.order_by("-published_date")[:5],
        "num_redactors": num_redactors,
        "num_topics": num_topics,
        "num_newspapers": num_newspapers,
        "num_visits": num_visits + 1,
    }

    return render(request, "newspaper/index.html", context=context)


class TopicListView(LoginRequiredMixin, generic.ListView):
    model = Topic
    paginate_by = 5
    queryset = Topic.objects.all()

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(TopicListView, self).get_context_data()

        name = self.request.GET.get("name", "")

        context["search_form"] = TopicSearchForm(initial={"name": name})

        return context

    def get_queryset(self):
        form = TopicSearchForm(self.request.GET)

        if form.is_valid():
            return self.queryset.filter(
                name__icontains=form.cleaned_data["name"]
            )

        return self.queryset


class TopicCreateView(LoginRequiredMixin, generic.CreateView):
    model = Topic
    fields = "__all__"
    success_url = reverse_lazy("newspaper:topic-list")


class TopicUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Topic
    fields = "__all__"
    success_url = reverse_lazy("newspaper:topic-list")


class TopicDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Topic
    success_url = reverse_lazy("newspaper:topic-list")


class NewspaperListView(LoginRequiredMixin, generic.ListView):
    model = Newspaper
    paginate_by = 5
    queryset = Newspaper.objects.select_related("topic")

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(NewspaperListView, self).get_context_data()

        title = self.request.GET.get("title", "")

        context["search_form"] = NewspaperSearchForm(initial={"title": title})

        return context

    def get_queryset(self):
        form = NewspaperSearchForm(self.request.GET)

        if form.is_valid():
            return self.queryset.filter(
                title__icontains=form.cleaned_data["title"]
            )

        return self.queryset


class NewspaperDetailView(LoginRequiredMixin, generic.DetailView):
    model = Newspaper


class NewspaperCreateView(LoginRequiredMixin, generic.CreateView):
    model = Newspaper
    form_class = NewspaperForm
    success_url = reverse_lazy("newspaper:newspaper-list")


class NewspaperUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Newspaper
    form_class = NewspaperForm
    success_url = reverse_lazy("newspaper:newspaper-list")


class NewspaperDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Newspaper
    success_url = reverse_lazy("newspaper:newspaper-list")


class RedactorListView(LoginRequiredMixin, generic.ListView):
    model = Redactor
    paginate_by = 5
    queryset = Redactor.objects.all()

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(RedactorListView, self).get_context_data(**kwargs)

        username = self.request.GET.get("username", "")

        context["search_form"] = RedactorSearchForm(
            initial={"username": username}
        )

        return context

    def get_queryset(self):
        form = RedactorSearchForm(self.request.GET)

        if form.is_valid():
            return self.queryset.filter(
                username__icontains=form.cleaned_data["username"]
            )

        return self.queryset


class RedactorDetailView(LoginRequiredMixin, generic.DetailView):
    model = Redactor
    queryset = Redactor.objects.prefetch_related("newspaper__topic")


class RedactorCreationView(LoginRequiredMixin, generic.CreateView):
    model = Redactor
    form_class = RedactorCreationForm
    success_url = reverse_lazy("newspaper:redactor-list")


class RedactorUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Redactor
    form_class = RedactorUpdateForm
    success_url = reverse_lazy("newspaper:redactor-list")


class RedactorDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Redactor
    success_url = reverse_lazy("newspaper:redactor-list")


@login_required
def toggle_assign_to_newspaper(request, pk):
    redactor = Redactor.objects.get(id=request.user.id)
    if Newspaper.objects.get(id=pk) in redactor.newspaper.all():
        redactor.newspaper.remove(pk)
    else:
        redactor.newspaper.add(pk)
    return HttpResponseRedirect(
        reverse_lazy("newspaper:newspaper-detail", args=[pk])
    )

templates/newspaper/newspaper_detail.html
{% extends 'layouts/base.html' %}
{% load crispy_forms_filters %}

{% block title %} Details {% endblock title %}

{% block content %}

  <div class="header bg-primary pb-6">
    <div class="container-fluid">
      <div class="header-body">
        <div class="row align-items-center py-4">
          <div class="col-lg-6 col-7">
            <nav aria-label="breadcrumb" class="d-none d-md-inline-block ml-md-0">
              <ol class="breadcrumb breadcrumb-links breadcrumb-dark">
                <li class="breadcrumb-item"><a href="/"><i class="fas fa-home"></i></a></li>
                <li class="breadcrumb-item">
                  <a href="{% url 'newspaper:newspaper-list' %}">
                    Newspaper
                  </a>
                </li>
                <li class="breadcrumb-item">
                  <a href="{% url 'newspaper:newspaper-detail' pk=newspaper.id %}">
                    {{ newspaper.id }}
                  </a>
                </li>
              </ol>
            </nav>
          </div>
        </div>
      </div>
    </div>
  </div>

  <!-- Page content -->
  <div class="container-fluid mt--6">
    <div class="row">
      <div class="col">
        <div class="card">
          <!-- Card header -->
          <div class="card-header border-0 text-center">
            <h3 class="h1 mb-0">NEWSPAPER DETAIL</h3>
          </div>
          <!-- Content -->
          <div class="table-responsive">
            <div class="m-4">
              <p class="h2"><strong>{{ newspaper.title }}</strong></p>
              <p><strong>Topic:</strong> {{ newspaper.topic.name }}</p>
              <p><strong>Published date:</strong> {{ newspaper.published_date }}</p>
              <p class="h3">
                Redactors:
                {% if user not in newspaper.redactor.all %}
                  <a style="float: right"
                     href="{% url 'newspaper:toggle_assign_to_newspaper' pk=newspaper.id %}"
                     class="btn btn-sm btn-success">
                    Assign me to this newspaper
                  </a>
                {% else %}
                  <a style="float: right"
                     href="{% url 'newspaper:toggle_assign_to_newspaper' pk=newspaper.id %}"
                     class="btn btn-sm btn-danger">
                    Delete me from this newspaper
                  </a>
                {% endif %}
              </p>
              <ul>
                {% for redactor in newspaper.redactor.all %}
                  <li>
                    <strong><a href="{% url 'newspaper:redactor-detail' pk=redactor.id %}">{{ redactor.first_name }} {{ redactor.last_name }}</a></strong>
                    (Years of experience: {{ redactor.years_of_experience }})
                  </li>
                {% endfor %}
              </ul>
              <hr>
              <p class="h3">Text:</p>
              <p>{{ newspaper.content }}</p>
              <a href="{% url 'newspaper:newspaper-update' pk=newspaper.id %}" class="btn btn-sm btn-primary">Update</a>
              <a href="{% url 'newspaper:newspaper-delete' pk=newspaper.id %}" class="btn btn-sm btn-danger">Delete</a>
            </div>
          </div>
        </div>
      </div>
    </div>

    {% include "includes/footer.html" %}

  </div>

{% endblock content %}

<!-- Specific JS goes HERE -->
{% block javascripts %}{% endblock javascripts %}

templates/newspaper/newspaper_list.html
{% extends 'layouts/base.html' %}

{% block title %} Tables {% endblock title %}

{% block content %}

  <div class="header bg-primary pb-6">
    <div class="container-fluid">
      <div class="header-body">
        <div class="row align-items-center py-4">
          <div class="col-lg-6 col-7">
            <nav aria-label="breadcrumb" class="d-none d-md-inline-block ml-md-4">
              <ol class="breadcrumb breadcrumb-links breadcrumb-dark">
                <li class="breadcrumb-item"><a href="/"><i class="fas fa-home"></i></a></li>
                <li class="breadcrumb-item"><a href="{{ request.path }}">Newspaper</a></li>
              </ol>
            </nav>
          </div>
          <div class="col-lg-6 col-5 text-right">
            <a href="{% url 'newspaper:newspaper-create' %}" class="btn btn-sm btn-neutral">Create new news</a>
          </div>
        </div>
      </div>
    </div>
  </div>

  <!-- Page content -->
  <div class="container-fluid mt--6">
    <div class="row">
      <div class="col">
        {% if newspaper_list %}
          <h3 class="font-weight-bolder text-center text-white">NEWSPAPER TABLE</h3>
          <div class="card">
            <!-- Card header -->
            <div class="card-header border-0">
              <form action="" method="get" class="mb-0 form-inline">
                {{ search_form }}
                <input class="btn btn-sm btn-primary" type="submit" value="🔍 Search">
              </form>
            </div>
            <!-- Table -->
            <div class="table-responsive">
              <table class="table align-items-center table-flush">
                <thead class="thead-light">
                  <tr>
                    <th scope="col" class="sort text-center" data-sort="name">ID</th>
                    <th scope="col" class="sort text-center" data-sort="budget">Title</th>
                    <th scope="col" class="sort text-center" data-sort="status">Update</th>
                    <th scope="col" class="sort text-center" data-sort="completion">Delete</th>
                  </tr>
                </thead>
                <tbody class="list">
                  {% for newspaper in newspaper_list %}
                    <tr>
                      <th scope="row" class="text-center">
                        <a href="{% url 'newspaper:newspaper-detail' pk=newspaper.id %}">{{ newspaper.id }}</a>
                      </th>
                      <td class="budget text-center">
                        {{ newspaper.title }}
                      </td>
                      <td class="text-center">
                        <a href="{% url 'newspaper:newspaper-update' pk=newspaper.id %}" class="btn btn-sm btn-success">
                          Update
                        </a>
                      </td>
                      <td class="text-center">
                        <a href="{% url 'newspaper:newspaper-delete' pk=newspaper.id %}" class="btn btn-sm btn-danger">
                          Delete
                        </a>
                      </td>
                    </tr>
                  {% endfor %}
                </tbody>
              </table>
            </div>
            <!-- Card footer -->
            {% include "includes/pagination.html" %}
          </div>
        {% else %}
          <div class="card">
            <div class="card-header border-0">
              <p class="h1 text-center font-weight-bold pb-300">There are no newspapers in the agency.</p>
            </div>
          </div>
        {% endif %}
      </div>
    </div>

    {% include "includes/footer.html" %}

  </div>

{% endblock content %}

<!-- Specific JS goes HERE -->
{% block javascripts %}{% endblock javascripts %}

templates/newspaper/redactor_detail.html
{% extends 'layouts/base.html' %}

{% block title %} Profile {% endblock title %}

{% block content %}

<div class="header pb-6 d-flex align-items-center" style="min-height: 500px; background-image: url(/static/assets/img/theme/profile-cover.jpg); background-size: cover; background-position: center top;">
  <!-- Mask -->
  <span class="mask bg-gradient-default opacity-8"></span>
  <!-- Header container -->
  <div class="container-fluid d-flex align-items-center">
    <div class="row">
      <div class="col-lg-12 col-md-10">
        <h1 class="display-2 text-white">
          Hello {{ request.user.username }} ({{ request.user.first_name }})
        </h1>
        <p class="text-white mt-0 mb-5">
          This is {% if redactor == request.user %} your {% else %} {{ redactor.username }} {% endif %}
          profile page. You can see, update or delete
          {% if redactor == request.user %} your {% else %} {{ redactor.username }} {% endif %} information.
        </p>
        <span>
          <a href="{% url 'newspaper:redactor-list' %}" class="btn btn-neutral">Show all redactors</a>
        </span>
      </div>
    </div>
  </div>
</div>
<!-- Page content -->
<div class="container-fluid mt--6">
  <div class="row">
    <div class="col-xl-4 order-xl-2">
      <div class="card card-profile">
        <img src="/static/assets/img/theme/img-1-1000x600.jpg" alt="Image placeholder" class="card-img-top">
        <div class="row justify-content-center">
          <div class="col-lg-3 order-lg-2">
            <div class="card-profile-image">
              <img src="/static/assets/img/theme/team-4.jpg" class="rounded-circle">
            </div>
          </div>
        </div>
        <div class="card-header text-center border-0 pt-8 pt-md-4 pb-0 pb-md-4">
          <div class="d-flex justify-content-between">
            <a href="{% url 'newspaper:redactor-update' pk=redactor.id %}" class="btn btn-sm btn-info  mr-4 ">Update</a>
            <a href="{% url 'newspaper:redactor-delete' pk=redactor.id %}" class="btn btn-sm btn-danger float-right">Delete</a>
          </div>
        </div>
        <div class="card-body pt-0">
          <div class="text-center">
            <h5 class="h3">
              {{ redactor.username }}
            </h5>
            <div class="h5 font-weight-300">
              {{ redactor.email }}
            </div>
            <div class="h5 font-weight-300">
              Personal ID: {{ redactor.id }}
            </div>
            <div class="h2 mt-4">
              {{ redactor.first_name }} {{ redactor.last_name }}
            </div>
            <div>
              <p>{{ redactor.years_of_experience }} year{{ redactor.years_of_experience|pluralize }} of experience</p>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="col-xl-8 order-xl-1">
      <div class="card">
        <div class="card-header">
          <div class="row align-items-center">
            <div class="col-8">
              <h3 class="mb-0">Job information</h3>
            </div>
          </div>
        </div>
        <div class="card-body">
          <form>
            <h6 class="heading text-muted mb-4">Newspapers</h6>
            {% for newspaper in redactor.newspaper.all %}
              <hr>
              <p>
                <strong>Title:</strong>
                <a class="text-underline" href="{% url 'newspaper:newspaper-detail' pk=newspaper.id %}">{{ newspaper.title }}</a>
              </p>
              <p><strong>Topic:</strong> {{ newspaper.topic.name }}</p>
              <p><strong>Newspaper ID:</strong> {{newspaper.id}}</p>
            {% empty %}
              <p>No newspapers!</p>
            {% endfor %}
          </form>
        </div>
      </div>
    </div>
  </div>

  {% include "includes/footer.html" %}

</div>

{% endblock content %}

<!-- Specific JS goes HERE -->
{% block javascripts %}{% endblock javascripts %}

templates/newspaper/topic_list.html
{% extends 'layouts/base.html' %}

{% block title %} Tables {% endblock title %}

{% block content %}

  <div class="header bg-primary pb-6">
    <div class="container-fluid">
      <div class="header-body">
        <div class="row align-items-center py-4">
          <div class="col-lg-6 col-7">
            <nav aria-label="breadcrumb" class="d-none d-md-inline-block ml-md-0">
              <ol class="breadcrumb breadcrumb-links breadcrumb-dark">
                <li class="breadcrumb-item"><a href="/"><i class="fas fa-home"></i></a></li>
                <li class="breadcrumb-item"><a href="{{ request.path }}">Topic</a></li>
              </ol>
            </nav>
          </div>
          <div class="col-lg-6 col-5 text-right">
            <a href="{% url 'newspaper:topic-create' %}" class="btn btn-sm btn-neutral">Create new topic</a>
          </div>
        </div>
      </div>
    </div>
  </div>

  <!-- Page content -->
  <div class="container-fluid mt--6">
    <div class="row">
      <div class="col">
        {% if topic_list %}
          <h3 class="font-weight-bolder text-center text-white">TOPIC TABLE</h3>
          <div class="card">
            <!-- Card header -->
            <div class="card-header border-0">
              <form action="" method="get" class="mb-0 form-inline">
                {{ search_form }}
                <input class="btn btn-sm btn-primary" type="submit" value="🔍 Search">
              </form>
            </div>
            <!-- Table -->
            <div class="table-responsive">
              <table class="table align-items-center table-flush">
                <thead class="thead-light">
                  <tr>
                    <th scope="col" class="sort text-center" data-sort="name">ID</th>
                    <th scope="col" class="sort text-center" data-sort="budget">Topic</th>
                    <th scope="col" class="sort text-center" data-sort="status">Update</th>
                    <th scope="col" class="sort text-center" data-sort="completion">Delete</th>
                  </tr>
                </thead>
                <tbody class="list">
                  {% for topic in topic_list %}
                    <tr>
                      <th scope="row" class="text-center">
                        {{ topic.id }}
                      </th>
                      <td class="budget text-center">
                        {{ topic.name }}
                      </td>
                      <td class="text-center">
                        <a href="{% url 'newspaper:topic-update' pk=topic.id %}" class="btn btn-sm btn-success">
                          Update
                        </a>
                      </td>
                      <td class="text-center">
                        <a href="{% url 'newspaper:topic-delete' pk=topic.id %}" class="btn btn-sm btn-danger">
                          Delete
                        </a>
                      </td>
                    </tr>
                  {% endfor %}
                </tbody>
              </table>
            </div>
            <!-- Card footer -->
            {% include "includes/pagination.html" %}
          </div>
        {% else %}
          <div class="card">
            <div class="card-header border-0">
              <p class="h1 text-center font-weight-bold pb-300">There are no topics in the agency.</p>
            </div>
          </div>
        {% endif %}
      </div>
    </div>

    {% include "includes/footer.html" %}

  </div>

{% endblock content %}

<!-- Specific JS goes HERE -->
{% block javascripts %}{% endblock javascripts %}